///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodPressureModelResponse {
/*
{
  "blood_pressure": "120/80",
  "date": "November 16, 2023",
  "time": "1:21 AM"
}
*/

  String? bloodPressure;
  String? date;
  String? time;

  BloodPressureModelResponse({
    this.bloodPressure,
    this.date,
    this.time,
  });
  BloodPressureModelResponse.fromJson(Map<String, dynamic> json) {
    bloodPressure = json['blood_pressure']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['blood_pressure'] = bloodPressure;
    data['date'] = date;
    data['time'] = time;
    return data;
  }
}

class BloodPressureModel {
/*
{
  "statusCode": 200,
  "message": "Blood Pressure data retrieved Successfully",
  "response": [
    {
      "blood_pressure": "120/80",
      "date": "November 16, 2023",
      "time": "1:21 AM"
    }
  ]
}
*/

  int? statusCode;
  String? message;
  List<BloodPressureModelResponse?>? response;

  BloodPressureModel({
    this.statusCode,
    this.message,
    this.response,
  });
  BloodPressureModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    if (json['response'] != null) {
      final v = json['response'];
      final arr0 = <BloodPressureModelResponse>[];
      v.forEach((v) {
        arr0.add(BloodPressureModelResponse.fromJson(v));
      });
      response = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (response != null) {
      final v = response;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['response'] = arr0;
    }
    return data;
  }
}
