///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodSugarModelResponse {
/*
{
  "blood_sugar": "84",
  "date": "November 15, 2023",
  "time": "12:25 PM"
}
*/

  String? bloodSugar;
  String? date;
  String? time;

  BloodSugarModelResponse({
    this.bloodSugar,
    this.date,
    this.time,
  });
  BloodSugarModelResponse.fromJson(Map<String, dynamic> json) {
    bloodSugar = json['blood_sugar']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['blood_sugar'] = bloodSugar;
    data['date'] = date;
    data['time'] = time;
    return data;
  }
}

class BloodSugarModel {
/*
{
  "statusCode": 200,
  "message": "Blood Sugar data retrieved Successfully",
  "response": [
    {
      "blood_sugar": "84",
      "date": "November 15, 2023",
      "time": "12:25 PM"
    }
  ]
}
*/

  int? statusCode;
  String? message;
  List<BloodSugarModelResponse?>? response;

  BloodSugarModel({
    this.statusCode,
    this.message,
    this.response,
  });
  BloodSugarModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    if (json['response'] != null) {
      final v = json['response'];
      final arr0 = <BloodSugarModelResponse>[];
      v.forEach((v) {
        arr0.add(BloodSugarModelResponse.fromJson(v));
      });
      response = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (response != null) {
      final v = response;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['response'] = arr0;
    }
    return data;
  }
}
