///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodCholesterolModelResponse {
/*
{
  "blood_cholesterol": "85",
  "date": "November 15, 2023",
  "time": "10:35 PM"
}
*/

  String? bloodCholesterol;
  String? date;
  String? time;

  BloodCholesterolModelResponse({
    this.bloodCholesterol,
    this.date,
    this.time,
  });
  BloodCholesterolModelResponse.fromJson(Map<String, dynamic> json) {
    bloodCholesterol = json['blood_cholesterol']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['blood_cholesterol'] = bloodCholesterol;
    data['date'] = date;
    data['time'] = time;
    return data;
  }
}

class BloodCholesterolModel {
/*
{
  "statusCode": 200,
  "message": "Blood Cholesterol data retrieved Successfully",
  "response": [
    {
      "blood_cholesterol": "85",
      "date": "November 15, 2023",
      "time": "10:35 PM"
    }
  ]
}
*/

  int? statusCode;
  String? message;
  List<BloodCholesterolModelResponse?>? response;

  BloodCholesterolModel({
    this.statusCode,
    this.message,
    this.response,
  });
  BloodCholesterolModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    if (json['response'] != null) {
      final v = json['response'];
      final arr0 = <BloodCholesterolModelResponse>[];
      v.forEach((v) {
        arr0.add(BloodCholesterolModelResponse.fromJson(v));
      });
      response = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (response != null) {
      final v = response;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['response'] = arr0;
    }
    return data;
  }
}
