///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HeartRateModelResponse {
/*
{
  "heart_rate": "151",
  "date": "November 16, 2023",
  "time": "1:26 AM"
}
*/

  String? heartRate;
  String? date;
  String? time;

  HeartRateModelResponse({
    this.heartRate,
    this.date,
    this.time,
  });
  HeartRateModelResponse.fromJson(Map<String, dynamic> json) {
    heartRate = json['heart_rate']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['heart_rate'] = heartRate;
    data['date'] = date;
    data['time'] = time;
    return data;
  }
}

class HeartRateModel {
/*
{
  "statusCode": 200,
  "message": "Heart Rate data retrieved Successfully",
  "response": [
    {
      "heart_rate": "151",
      "date": "November 16, 2023",
      "time": "1:26 AM"
    }
  ]
}
*/

  int? statusCode;
  String? message;
  List<HeartRateModelResponse?>? response;

  HeartRateModel({
    this.statusCode,
    this.message,
    this.response,
  });
  HeartRateModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    if (json['response'] != null) {
      final v = json['response'];
      final arr0 = <HeartRateModelResponse>[];
      v.forEach((v) {
        arr0.add(HeartRateModelResponse.fromJson(v));
      });
      response = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (response != null) {
      final v = response;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['response'] = arr0;
    }
    return data;
  }
}
