name: pharma_trac
description: A term 4 project for health care - adverse durg reactions
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.7
  http: ^1.1.0
  fluttertoast: ^8.2.2
  double_back_to_close_app: ^2.1.0
  dropdown_button2: ^2.3.9
  country_picker: ^2.0.21
  google_sign_in: ^6.1.5
  realm: ^1.5.0
  auto_route: ^7.8.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  device_preview: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - Icons/
