///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MedicineListModel {
/*
{
  "statusCode": "200",
  "data": [
    "abilify"
  ]
}
*/

  String? statusCode;
  List<String?>? data;

  MedicineListModel({
    this.statusCode,
    this.data,
  });
  MedicineListModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['data'] = arr0;
    }
    return data;
  }
}
