///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MedicineSideEffectsResponse {
/*
{
  "statusCode": "200",
  "medicine_name": "azithromycin",
  "data": [
    "diarrhea"
  ]
}
*/

  String? statusCode;
  String? medicineName;
  List<String?>? data;

  MedicineSideEffectsResponse({
    this.statusCode,
    this.medicineName,
    this.data,
  });
  MedicineSideEffectsResponse.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toString();
    medicineName = json['medicine_name']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['medicine_name'] = medicineName;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['data'] = arr0;
    }
    return data;
  }
}
