///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginUserResponse {
/*
{
  "_id": "6557f68521f7dcc7830b8a45",
  "email_address": "sanjay@gmail.com",
  "password": "$2b$10$SYWe6seK2aOAsgYjeRPO1OvCUj2Wy4IgOG2HPeBauJaBTN5PhEWgq",
  "fullName": "Sanjay Sharma",
  "confirmPassword": "Vir@l2330",
  "birthDate": "5/16/1865",
  "gender": "male",
  "country": "Canada",
  "height": "85",
  "weight": "120"
}
*/

  String? Id;
  String? emailAddress;
  String? password;
  String? fullName;
  String? confirmPassword;
  String? birthDate;
  String? gender;
  String? country;
  String? height;
  String? weight;

  LoginUserResponse({
    this.Id,
    this.emailAddress,
    this.password,
    this.fullName,
    this.confirmPassword,
    this.birthDate,
    this.gender,
    this.country,
    this.height,
    this.weight,
  });
  LoginUserResponse.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    emailAddress = json['email_address']?.toString();
    password = json['password']?.toString();
    fullName = json['fullName']?.toString();
    confirmPassword = json['confirmPassword']?.toString();
    birthDate = json['birthDate']?.toString();
    gender = json['gender']?.toString();
    country = json['country']?.toString();
    height = json['height']?.toString();
    weight = json['weight']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['email_address'] = emailAddress;
    data['password'] = password;
    data['fullName'] = fullName;
    data['confirmPassword'] = confirmPassword;
    data['birthDate'] = birthDate;
    data['gender'] = gender;
    data['country'] = country;
    data['height'] = height;
    data['weight'] = weight;
    return data;
  }
}

class LoginUser {
/*
{
  "statusCode": 200,
  "message": "User logged in successfully",
  "response": {
    "_id": "6557f68521f7dcc7830b8a45",
    "email_address": "sanjay@gmail.com",
    "password": "$2b$10$SYWe6seK2aOAsgYjeRPO1OvCUj2Wy4IgOG2HPeBauJaBTN5PhEWgq",
    "fullName": "Sanjay Sharma",
    "confirmPassword": "Vir@l2330",
    "birthDate": "5/16/1865",
    "gender": "male",
    "country": "Canada",
    "height": "85",
    "weight": "120"
  }
}
*/

  int? statusCode;
  String? message;
  LoginUserResponse? response;

  LoginUser({
    this.statusCode,
    this.message,
    this.response,
  });
  LoginUser.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    response = (json['response'] != null) ? LoginUserResponse.fromJson(json['response']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
