///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateUserResponseUpdatedUser {
/*
{
  "_id": "6548718fd35014483907d86d",
  "email_address": "hvms2330@gmail.com",
  "password": "Vir@l2330",
  "fullName": "Viral Siddhapura",
  "confirmPassword": "Vir@l2330",
  "birthDate": "6/11/2023",
  "gender": "Female",
  "country": "Afghanistan",
  "height": "56",
  "weight": "86"
}
*/

  String? Id;
  String? emailAddress;
  String? password;
  String? fullName;
  String? confirmPassword;
  String? birthDate;
  String? gender;
  String? country;
  String? height;
  String? weight;

  UpdateUserResponseUpdatedUser({
    this.Id,
    this.emailAddress,
    this.password,
    this.fullName,
    this.confirmPassword,
    this.birthDate,
    this.gender,
    this.country,
    this.height,
    this.weight,
  });
  UpdateUserResponseUpdatedUser.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    emailAddress = json['email_address']?.toString();
    password = json['password']?.toString();
    fullName = json['fullName']?.toString();
    confirmPassword = json['confirmPassword']?.toString();
    birthDate = json['birthDate']?.toString();
    gender = json['gender']?.toString();
    country = json['country']?.toString();
    height = json['height']?.toString();
    weight = json['weight']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['email_address'] = emailAddress;
    data['password'] = password;
    data['fullName'] = fullName;
    data['confirmPassword'] = confirmPassword;
    data['birthDate'] = birthDate;
    data['gender'] = gender;
    data['country'] = country;
    data['height'] = height;
    data['weight'] = weight;
    return data;
  }
}

class UpdateUserResponse {
/*
{
  "message": "User updated successfully",
  "updatedUser": {
    "_id": "6548718fd35014483907d86d",
    "email_address": "hvms2330@gmail.com",
    "password": "Vir@l2330",
    "fullName": "Viral Siddhapura",
    "confirmPassword": "Vir@l2330",
    "birthDate": "6/11/2023",
    "gender": "Female",
    "country": "Afghanistan",
    "height": "56",
    "weight": "86"
  }
}
*/

  String? message;
  UpdateUserResponseUpdatedUser? updatedUser;

  UpdateUserResponse({
    this.message,
    this.updatedUser,
  });
  UpdateUserResponse.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    updatedUser = (json['updatedUser'] != null)
        ? UpdateUserResponseUpdatedUser.fromJson(json['updatedUser'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    if (updatedUser != null) {
      data['updatedUser'] = updatedUser!.toJson();
    }
    return data;
  }
}
