// class UserRegisterResponseModel {
//   int? statusCode;
//   String? message;
//   User? user;
//
//   UserRegisterResponseModel({this.statusCode, this.message, this.user});
//
//   UserRegisterResponseModel.fromJson(Map<String, dynamic> json) {
//     statusCode = json['statusCode'];
//     message = json['message'];
//     user = json['user'] != null ? User.fromJson(json['user']) : null;
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = <String, dynamic>{};
//     data['statusCode'] = statusCode;
//     data['message'] = message;
//     if (user != null) {
//       data['user'] = user!.toJson();
//     }
//     return data;
//   }
// }
//
// class User {
//   Id? iId;
//   String? emailAddress;
//   String? password;
//
//   User({this.iId, this.emailAddress, this.password});
//
//   User.fromJson(Map<String, dynamic> json) {
//     iId = json['id'] != null ? Id.fromJson(json['id']) : null;
//     emailAddress = json['email_address'];
//     password = json['password'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = <String, dynamic>{};
//     if (iId != null) {
//       data['id'] = iId!.toJson();
//     }
//     data['email_address'] = emailAddress;
//     data['password'] = password;
//     return data;
//   }
// }
//
// class Id {
//   String? oid;
//
//   Id({this.oid});
//
//   Id.fromJson(Map<String, dynamic> json) {
//     oid = json['$oid'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = <String, dynamic>{};
//     data['$oid'] = oid;
//     return data;
//   }
// }

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserRegisterResponseModelUser {
/*
{
  "acknowledged": true,
  "insertedId": "6549be73c197464fec9ef199"
}
*/

  bool? acknowledged;
  String? insertedId;

  UserRegisterResponseModelUser({
    this.acknowledged,
    this.insertedId,
  });
  UserRegisterResponseModelUser.fromJson(Map<String, dynamic> json) {
    acknowledged = json['acknowledged'];
    insertedId = json['insertedId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['acknowledged'] = acknowledged;
    data['insertedId'] = insertedId;
    return data;
  }
}

class UserRegisterResponseModel {
/*
{
  "statusCode": 200,
  "message": "User Register successfully",
  "user": {
    "acknowledged": true,
    "insertedId": "6549be73c197464fec9ef199"
  }
}
*/

  int? statusCode;
  String? message;
  UserRegisterResponseModelUser? user;

  UserRegisterResponseModel({
    this.statusCode,
    this.message,
    this.user,
  });
  UserRegisterResponseModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    user = (json['user'] != null) ? UserRegisterResponseModelUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}

